export const applicationTypes = () => {
  return {
    SET_WALLET_RPC: 'SET_WALLET_RPC',
    SET_WEB3: 'SET_WEB3',
    SET_NOT_CORRECT_CHAIN: 'SET_NOT_CORRECT_CHAIN',
    SET_DEFAULT_REFERRER: 'SET_DEFAULT_REFERRER',
    SET_TOTAL_BNB_DEPOSIT: 'SET_TOTAL_BNB_DEPOSIT',
    SET_PARTICIPANTS: 'SET_PARTICIPANTS',
    SET_CONTRACT_PERCENT: 'SET_CONTRACT_PERCENT'
  }
}
