export const accountTypes = () => {
  return {
    SET_USER_STATS: 'SET_USER_STATS',
    SET_USER_INFO: 'SET_USER_INFO',
    SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
    SET_BNB_BALANCE: 'SET_BNB_BALANCE',
    SET_BNB_INVEST_INPUT: "SET_BNB_INVEST_INPUT"
  }
}
